version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4444
      MYSQL_DATABASE: Prueba
      MYSQL_USER: Santic
      MYSQL_PASSWORD: 12345678
    ports:
      - '3307:3306'
      
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db